build:
    docker build -t my_flask_app .

run:
    docker run -d -p 5000:5000 my_flask_app

stop:
    docker stop $(docker ps -aq --filter ancestor=my_flask_app)

clean:
    docker system prune -a --volumes
